language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo

before_install:
  - rustup component add clippy
  - rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy

script:
  - cargo build --verbose --all
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --verbose --all

